import type { Metadata } from "next";
import "@/styles/globals.sass";
import MainLayout from "@/layout/main-layout";
import { ILayout } from "@/layout/lauout.interface";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({children}: ILayout) => {
  return <MainLayout>{children}</MainLayout>
}
export default RootLayout;